name: cyclic_UCLA_Class_multi_label
model_type: ImageClassificationModel
scale: 1
num_gpu: 6
manual_seed: 3407

datasets:
  train:
    data_file: ./data_info/UCLA_train.txt
    type: PairedSmriDataset_class
    dataroot_gt: ./UCLA_clean
    dataroot_lq: ./UCLA_corrupted

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda # ataloader for CUDAPrefetcher
    pin_memory: true

  val:
    data_file: ./data_info/UCLA_test.txt
    type: PairedSmriDataset_class
    dataroot_gt: ./UCLA_clean
    dataroot_lq: ./UCLA_corrupted


# network structures
network_g:
  type: Cyclic_Classfier
  hin_position_left: 0
  hin_position_right: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100001
    eta_min: !!float 1e-6

  total_iter: 100001
  warmup_iter: -1 # no warm up

# validation settings
val:
  val_freq: 100
  save_img: false
  max_minibatch: 4

  metrics:
    acc:
      type: calculate_acc

      
# logging settings
logger:
  print_freq: 1
  # save_checkpoint_freq: !!float 5e4
  save_checkpoint_freq: 100
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
